.data
.text
 
 add $t0, $t0, 5
 sw $t0 ($t1)
 add $t0, $t0, 9 # EXECUTE THE INSTRUCTION AFTER THE HANDLER EXCEPTION

.ktext 0x80000180
  mfc0 $k0, $14 # LOADED WITH THE CONTENT OF THE COPRECESSOR 14 ( ADDRESS LOAD EXCEPTION)
  mfc0 $k1, $13 # UNDERSTAND THE CAUSE
  srl  $t2, $k1,2 # SHIFT RIGHT TO TAKE THE EXCEPTION
  addi $k0, $k0, 4 # SKIPPED NEXT ADDRESSS IN THE MEMORY AND SKIPPED THE ISSUE
  mtc0 $k0, $14 # STORED IN COPRECESSOR REGISTER 14
  eret # 
 
  
